/*
 * This file was auto-generated by speedy-antlr-tool v1.3.1
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#include "sa_zoia_translator.h"


SA_zoiaTranslator::SA_zoiaTranslator(speedy_antlr::Translator *translator) {
    this->translator = translator;
}

SA_zoiaTranslator::~SA_zoiaTranslator() {
    Py_XDECREF(ZoiaFileContext_cls);
    Py_XDECREF(HeaderContext_cls);
    Py_XDECREF(LineContext_cls);
    Py_XDECREF(LineElementsContext_cls);
    Py_XDECREF(RegularLineElementsContext_cls);
    Py_XDECREF(LineElementContext_cls);
    Py_XDECREF(MarkedUpLineElementsContext_cls);
    Py_XDECREF(BoldItalicLineElementsContext_cls);
    Py_XDECREF(BoldLineElementsContext_cls);
    Py_XDECREF(ItalicLineElementsContext_cls);
    Py_XDECREF(TextFragmentContext_cls);
    Py_XDECREF(AliasContext_cls);
    Py_XDECREF(CommandContext_cls);
    Py_XDECREF(ArgumentsContext_cls);
    Py_XDECREF(ArgumentContext_cls);
    Py_XDECREF(KwdArgumentContext_cls);
    Py_XDECREF(StdArgumentContext_cls);
    Py_XDECREF(WhitespaceContext_cls);
}


antlrcpp::Any SA_zoiaTranslator::visitZoiaFile(zoiaParser::ZoiaFileContext *ctx){
    if(!ZoiaFileContext_cls) ZoiaFileContext_cls = PyObject_GetAttrString(translator->parser_cls, "ZoiaFileContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ZoiaFileContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitHeader(zoiaParser::HeaderContext *ctx){
    if(!HeaderContext_cls) HeaderContext_cls = PyObject_GetAttrString(translator->parser_cls, "HeaderContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, HeaderContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitLine(zoiaParser::LineContext *ctx){
    if(!LineContext_cls) LineContext_cls = PyObject_GetAttrString(translator->parser_cls, "LineContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LineContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitLineElements(zoiaParser::LineElementsContext *ctx){
    if(!LineElementsContext_cls) LineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "LineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitRegularLineElements(zoiaParser::RegularLineElementsContext *ctx){
    if(!RegularLineElementsContext_cls) RegularLineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "RegularLineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, RegularLineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitLineElement(zoiaParser::LineElementContext *ctx){
    if(!LineElementContext_cls) LineElementContext_cls = PyObject_GetAttrString(translator->parser_cls, "LineElementContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, LineElementContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitMarkedUpLineElements(zoiaParser::MarkedUpLineElementsContext *ctx){
    if(!MarkedUpLineElementsContext_cls) MarkedUpLineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "MarkedUpLineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, MarkedUpLineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitBoldItalicLineElements(zoiaParser::BoldItalicLineElementsContext *ctx){
    if(!BoldItalicLineElementsContext_cls) BoldItalicLineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "BoldItalicLineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, BoldItalicLineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitBoldLineElements(zoiaParser::BoldLineElementsContext *ctx){
    if(!BoldLineElementsContext_cls) BoldLineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "BoldLineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, BoldLineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitItalicLineElements(zoiaParser::ItalicLineElementsContext *ctx){
    if(!ItalicLineElementsContext_cls) ItalicLineElementsContext_cls = PyObject_GetAttrString(translator->parser_cls, "ItalicLineElementsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ItalicLineElementsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitTextFragment(zoiaParser::TextFragmentContext *ctx){
    if(!TextFragmentContext_cls) TextFragmentContext_cls = PyObject_GetAttrString(translator->parser_cls, "TextFragmentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, TextFragmentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitAlias(zoiaParser::AliasContext *ctx){
    if(!AliasContext_cls) AliasContext_cls = PyObject_GetAttrString(translator->parser_cls, "AliasContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, AliasContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitCommand(zoiaParser::CommandContext *ctx){
    if(!CommandContext_cls) CommandContext_cls = PyObject_GetAttrString(translator->parser_cls, "CommandContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, CommandContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitArguments(zoiaParser::ArgumentsContext *ctx){
    if(!ArgumentsContext_cls) ArgumentsContext_cls = PyObject_GetAttrString(translator->parser_cls, "ArgumentsContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ArgumentsContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitArgument(zoiaParser::ArgumentContext *ctx){
    if(!ArgumentContext_cls) ArgumentContext_cls = PyObject_GetAttrString(translator->parser_cls, "ArgumentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, ArgumentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitKwdArgument(zoiaParser::KwdArgumentContext *ctx){
    if(!KwdArgumentContext_cls) KwdArgumentContext_cls = PyObject_GetAttrString(translator->parser_cls, "KwdArgumentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, KwdArgumentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitStdArgument(zoiaParser::StdArgumentContext *ctx){
    if(!StdArgumentContext_cls) StdArgumentContext_cls = PyObject_GetAttrString(translator->parser_cls, "StdArgumentContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, StdArgumentContext_cls);
    return py_ctx;
}

antlrcpp::Any SA_zoiaTranslator::visitWhitespace(zoiaParser::WhitespaceContext *ctx){
    if(!WhitespaceContext_cls) WhitespaceContext_cls = PyObject_GetAttrString(translator->parser_cls, "WhitespaceContext");
    PyObject *py_ctx = translator->convert_ctx(this, ctx, WhitespaceContext_cls);
    return py_ctx;
}
