/*
 * This file was auto-generated by speedy-antlr-tool v1.3.1
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "zoiaBaseVisitor.h"
#include "speedy_antlr.h"

class SA_zoiaTranslator : public zoiaBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *ZoiaFileContext_cls = NULL;
    PyObject *HeaderContext_cls = NULL;
    PyObject *LineContext_cls = NULL;
    PyObject *LineElementsContext_cls = NULL;
    PyObject *RegularLineElementsContext_cls = NULL;
    PyObject *LineElementContext_cls = NULL;
    PyObject *MarkedUpLineElementsContext_cls = NULL;
    PyObject *BoldItalicLineElementsContext_cls = NULL;
    PyObject *BoldLineElementsContext_cls = NULL;
    PyObject *ItalicLineElementsContext_cls = NULL;
    PyObject *TextFragmentContext_cls = NULL;
    PyObject *WordContext_cls = NULL;
    PyObject *AliasContext_cls = NULL;
    PyObject *CommandContext_cls = NULL;
    PyObject *ArgumentsContext_cls = NULL;
    PyObject *ArgumentContext_cls = NULL;
    PyObject *KwdArgumentContext_cls = NULL;
    PyObject *StdArgumentContext_cls = NULL;
    PyObject *WhitespaceContext_cls = NULL;

    public:
    SA_zoiaTranslator(speedy_antlr::Translator *translator);
    ~SA_zoiaTranslator();
    antlrcpp::Any visitZoiaFile(zoiaParser::ZoiaFileContext *ctx);

    antlrcpp::Any visitHeader(zoiaParser::HeaderContext *ctx);

    antlrcpp::Any visitLine(zoiaParser::LineContext *ctx);

    antlrcpp::Any visitLineElements(zoiaParser::LineElementsContext *ctx);

    antlrcpp::Any visitRegularLineElements(zoiaParser::RegularLineElementsContext *ctx);

    antlrcpp::Any visitLineElement(zoiaParser::LineElementContext *ctx);

    antlrcpp::Any visitMarkedUpLineElements(zoiaParser::MarkedUpLineElementsContext *ctx);

    antlrcpp::Any visitBoldItalicLineElements(zoiaParser::BoldItalicLineElementsContext *ctx);

    antlrcpp::Any visitBoldLineElements(zoiaParser::BoldLineElementsContext *ctx);

    antlrcpp::Any visitItalicLineElements(zoiaParser::ItalicLineElementsContext *ctx);

    antlrcpp::Any visitTextFragment(zoiaParser::TextFragmentContext *ctx);

    antlrcpp::Any visitWord(zoiaParser::WordContext *ctx);

    antlrcpp::Any visitAlias(zoiaParser::AliasContext *ctx);

    antlrcpp::Any visitCommand(zoiaParser::CommandContext *ctx);

    antlrcpp::Any visitArguments(zoiaParser::ArgumentsContext *ctx);

    antlrcpp::Any visitArgument(zoiaParser::ArgumentContext *ctx);

    antlrcpp::Any visitKwdArgument(zoiaParser::KwdArgumentContext *ctx);

    antlrcpp::Any visitStdArgument(zoiaParser::StdArgumentContext *ctx);

    antlrcpp::Any visitWhitespace(zoiaParser::WhitespaceContext *ctx);

};