# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#
#   This file is part of Zoia, a language for writing fiction.
#   Copyright (C) 2021-2022 Infernio
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# =============================================================================
"""This package contains the generated lexer/parser/visitor classes. They are
generated from grammar/zoia.g4 by running scripts/build.sh. All files in this
module are licensed under the GPLv3 (see the notice above). The .py files only
lack the notice because they are automatically generated by ANTLR.

All imports should come directly from here - *never* import from the actual
files that define the classes. That way they can be moved around easily."""
from grammar.sa_zoia import *
from grammar.zoiaLexer import *
from grammar.zoiaParser import *
from grammar.zoiaVisitor import *
